name: apostalica_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_html: ^3.0.0
  flutter_inappwebview: ^6.1.5
  font_awesome_flutter: ^10.8.0
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  go_router: ^14.7.2
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  shared_preferences: ^2.2.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/apochicon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/img/dinosaur.png
    - assets/img/earthpic1.png
    - assets/img/manuscriptpic.png
    - assets/img/nature1.png
    - assets/img/aposicon.png
   

  fonts:
    - family: NotoSerifKannada
      fonts:
        - asset: assets/fonts/NotoSerifKannada-Bold.ttf
    - family: BalooTamma2Regular
      fonts:
        - asset: assets/fonts/BalooTamma2-Regular.ttf
    - family: BalooTamma2Medium
      fonts:
        - asset: assets/fonts/BalooTamma2-Medium.ttf
    - family: BalooTamma2ExtraBold
      fonts:
        - asset: assets/fonts/BalooTamma2-ExtraBold.ttf
    - family: BalooTamma2Bold
      fonts:
        - asset: assets/fonts/BalooTamma2-Bold.ttf